# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Datenanalyse - Eine Einführung für BWLer
author: Coding and Data
logo: "" #mylogo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force


sphinx:
  config:
    html_theme: quantecon_book_theme
    html_theme_options:
      header_organisation_url: https://www.fh-bielefeld.de
      header_organisation: FH Bielefeld
      repository_url: https://github.com/fredzett/CodingBook
      repository_branch: main
      launch_buttons:
        colab_url: https://colab.research.google.com
        binderhub_url: https://mybinder.org
      persistent_sidebar: true
      use_repository_button: false
      use_launch_button: true
      navbar_footer_text: "Dies ist ein Test"
      #nb_repository_url: https://github.com/QuantEcon/lecture-python-advanced.notebooks
      #twitter: quantecon
      #twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
      #og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
      #description: This website presents a set of lectures on advanced quantitative economic modeling, designed and written by Thomas J. Sargent and John Stachurski.
      #keywords: Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski
      #google_analytics_id: UA-54984338-11


# Define the name of the latex output file for PDF builds
#latex:
#  latex_documents:
#    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
#repository:
#  url: https://github.com/fredzett/codingbook  # Online location of your book
#  path_to_book: book  # Optional path to your book, relative to the repository root
#  branch: main # master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: false
#  use_repository_button: false

#launch_buttons:
#  colab_url: "https://colab.research.google.com"
#  binderhub_url: ""